# Generated by Django 3.2.16 on 2022-10-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('PSR', 'Poolside'), ('GVR', 'Garden View'), ('OVR', 'Ocean View'), ('SOS', 'Superior Ocean Suite')], max_length=3)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
            ],
        ),
    ]
