# Generated by Django 3.2.16 on 2022-10-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('confirmed', 'confirmed'), ('denied', 'denied')], default='requested', max_length=10),
        ),
    ]
