# Generated by Django 3.2.16 on 2022-10-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_type',
            new_name='room',
        ),
    ]
