# Generated by Django 3.2.16 on 2022-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20221013_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_children',
            field=models.IntegerField(choices=[(0, '0 children'), (1, '1 child'), (2, '2 children')], default=0),
        ),
    ]
